image: node:latest

stages:
  - pages

pages:
  stage: pages
  script:
    - curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
    - gunzip elm.gz
    - chmod +x elm
    - sudo mv elm /usr/local/bin/
    - npm install
    - npm run build
    - mkdir -p public/{dist,src}
    - cp dist/main.js public/dist/
    - cp src/midi.js public/src/
    - cp index.html public/

  artifacts:
    paths:
    - public
